### ISSUE TITLE
Client is not informed if remote user declines call

### ISSUE THREAD

**Issue by adamhusse818** [vcuse/SE-Neurology-WebClient#18]

**Comment by deHank** [comment]
Do you know if PeerJS sends any form of a notification when a user declines a call? If it doesn't, we'll have to add that functionality to the signaling server 

Here's the documentation: https://peerjs.com/docs/#api

**Comment by adamhusse818** [comment]
We do not need to change anything in the server. When a call is initiated, I also establish a connection between the peers, which allows for the calling and messaging at the same time. I can simply just close the connection between the peers when the decline button is clicked.
