### ISSUE TITLE
Declining Call Bugs

### ISSUE THREAD

**Issue by laurenviado** [vcuse/SE-Neurology-WebClient#29]
User who send out call doesn't get any notice that the call got declined

- ringing pop up doesn't go away
~~- camera feed doesn't stop~~
~~- feature request: pop up that says "User Declined.." and has an "Ok" dismiss button~~

**Comment by adamhusse818** [comment]
The other two issues mentioned were fixed and you can see them in my development branch. This one I left still needs work but the changes I made should help with it.

**Comment by laurenviado** [comment]
oh cool, if u create a pr and push it to main i can work on the last part
